/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2025-09-10

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "Includes/gpio.h"
#include "Includes/macros_utiles.h"
#include "Includes/delai.h"
#include "Includes/adc.h"
#include "Includes/pwm.h"
#include "Includes/controleurled.h"
#include "Includes/lcd_driver.h"
#include "Includes/spi.h"
#include "Includes/uart.h"
#include "Includes/affichage.h"



/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/

#define P2
#define RGB565_RED   0xF800
#define RGB565_GRN   0x07E0
#define RGB565_BLU   0x001F

int main(void)
{
	//MAIN DU LABO 3
	#ifdef P1
    SystemInit();
	SystemCoreClockUpdate();
	InitSysTick_1ms(SystemCoreClock);

    UART5_init(18000000, 115200);

    const char *msg = "Hello World!\r\n";
    uint8_t c;

    while (1) {
        //UART5_sendString(msg);
       // delay_ms_blocking(1000);

        // Echo: tout ce qu'on reçoit, on le renvoie
        while (UART5_getc_nonblocking(&c)) {
            UART5_putc(c);
        }
    }
	#endif

	#ifdef P2
	SystemCoreClockUpdate();
	InitSysTick_1ms(SystemCoreClock);
	LCD_InitGPIO();
	SPI_Init_ForLCD();
	LCD_InitSerialInterface();

	while (1) {
		LCD_CopyColorToFrameBuffer(RGB565_RED);
		LCD_TransmitFrameBuffer();
		delay_ms_blocking(1000);

		LCD_CopyColorToFrameBuffer(RGB565_GRN);
		LCD_TransmitFrameBuffer();
		delay_ms_blocking(1000);

		LCD_CopyColorToFrameBuffer(RGB565_BLU);
		LCD_TransmitFrameBuffer();
		delay_ms_blocking(1000);
	}
	#endif

	#ifdef P3
	SystemInit();
	SystemCoreClockUpdate();
	InitSysTick_1ms(SystemCoreClock);

	UART5_init(18000000, 115200);

	Affichage_Init();

	while (1)
	{
		Affichage_Update();  // lit la FIFO et affiche les caractères
	}
	

	

	#endif



	//MAIN DU LABO 2
	// #ifdef P1

	// 	GPIO_initPin(GPIOC,3,GPIO_ANALOG);
	// 	ADC_init(ADC1);
	// 	SystemCoreClockUpdate();
	// 	InitSysTick_1ms(SystemCoreClock);
	// 	timer_t t2hz;
	// 	timer_start(&t2hz);

	// 	GPIO_initPin(GPIOG,13,GPIO_OUTPUT);
	// 	uint8_t state = 0;

	// 	while (1) {
	// 		ADC_startConversion(ADC1);
	// 		delay_ms_blocking(100);
	// 		if (ADC_isReady()) {
	// 			uint16_t val = ADC_readValue();
	// 			state ^= 1;
	// 			GPIO_writePin(GPIOG,13, state);
	// 	        }
	// 	    }
	// #endif

	// #ifdef P2
	// 	SystemCoreClockUpdate();
	// 	uint32_t clock = SystemCoreClock/2; //Clock pour APB1 selectionner
	// 	// PWM_Init(clock, 100, 25);
	// 	// PWM_Init(clock, 400, 63);
	// 	PWM_Init(clock, 1000, 88);
	// 	while(1){}
	// #endif


	// #ifdef P3
	// 	controleurled_init(GPIOA,0,GPIOC,3,ADC1);
	// 	SystemCoreClockUpdate();
	// 	InitSysTick_1ms(SystemCoreClock);

	// 	timer_t t;
	// 	timer_start(&t);

	// 	while (1) {
	// 		if (controleurled_buttonPressed(GPIOA,0)) {
	// 			if (timer_expired(&t, 20)) {
	// 				timer_start(&t);
	// 				controleurled_turnOnOffLed(ON, ADC1);
	// 			}
	// 		} else {
	// 			if (timer_expired(&t, 20)) {
	// 				timer_start(&t);
	// 				controleurled_turnOnOffLed(OFF, ADC1);
	// 			}
	// 		}
	// 	}
	// #endif

	//MAIN DU LABO 1
	// #ifdef P1
	// 	GPIO_initPin(GPIOG,13,GPIO_OUTPUT);
	// 	GPIO_initPin(GPIOG,14,GPIO_OUTPUT);
	// 	GPIO_initPin(GPIOA,0,GPIO_INPUT);

	//     while (1)
	//     {
	//         if (GPIO_readPin(GPIOA,0))  // bouton enfonce
	//         {
	//         	GPIO_writePin(GPIOG,13,1); // LED pin13 actif
	// 			GPIO_writePin(GPIOG,14,0); // LED pin14 inactif
	//         }
	//         else
	//         {
	//         	GPIO_writePin(GPIOG,13,0); // LED pin13 inactif
	// 			GPIO_writePin(GPIOG,14,1); // LED pin14 actif
	//         }
	//     }
	// #endif

	// #ifdef P2
	//     GPIO_initPin(GPIOG,13,GPIO_OUTPUT);
	// 	GPIO_initPin(GPIOG,14,GPIO_OUTPUT);
	// 	GPIO_initPin(GPIOA,0,GPIO_INPUT);

	// 	SystemCoreClockUpdate();
	// 	InitSysTick_1ms(SystemCoreClock);

	// 	timer_t t2hz;
	// 	timer_start(&t2hz);
	// 	uint8_t state = 0;
	// 	uint8_t prev_pressed = 0;

	// 	GPIO_writePin(GPIOG,13,0);
	// 	GPIO_writePin(GPIOG,14,1);

	// 	while (1) {

	// 		uint8_t pressed = (uint8_t)GPIO_readPin(GPIOA, 0);

	// 		if (!pressed) {

	// 			GPIO_writePin(GPIOG,13,0);
	// 			GPIO_writePin(GPIOG,14,1);
	// 			delay_ms_blocking(500);

	// 			GPIO_writePin(GPIOG,13,1);
	// 			GPIO_writePin(GPIOG,14,0);
	// 			delay_ms_blocking(500);

	// 			prev_pressed = 0;
	// 		} else {

	// 			if (!prev_pressed) {
	// 				timer_start(&t2hz);
	// 				prev_pressed = 1;
	// 			}

	// 			if (timer_expired(&t2hz, 250)) {
	// 				timer_start(&t2hz);

	// 				state ^= 1;

	// 				GPIO_writePin(GPIOG,13, state);
	// 				GPIO_writePin(GPIOG,14, !state);
	// 			}

	// 		}
	// 	}
	// #endif
}

